apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  labels: 
    app: frontend
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: frontend
  template: 
    metadata: 
      labels: 
        app: frontend
    spec: 
      containers: 
      - name: frontend
        image: tjca1/frontend-redesocial:1.0.1-staging
        ports: 
        - containerPort: 80