---
apiVersion: v1
kind: Namespace
metadata: 
  name: staging
---
apiVersion: v1
kind: Namespace
metadata: 
  name: prod
---
apiVersion: v1
kind: Namespace
metadata: 
  name: devops
---
apiVersion: v1
kind: Namespace
metadata: 
  name: lab1
---
apiVersion: v1
kind: Namespace
metadata: 
  name: lab2
---
apiVersion: v1
kind: Namespace
metadata: 
  name: lab3