---
apiVersion: v1
kind: Secret
metadata:
  name: questcode
  namespace: staging
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly90amNhMTp0MTIzNDU2QGNsdXN0ZXIwLTlqYmJlLm1vbmdvZGIubmV0L3Rlc3Q/cmV0cnlXcml0ZXM9dHJ1ZQ==
  SECRET_OR_KEY: NjA0Mjk4NmE5YjM5ZjE1ZjI1YTM=
  GITHUB_CLIENT_SECRET: M2M4MmNmNjM5NmJlYjY4OWRkYmFlYWJhNGQ2YjYzNDYwMDI5NGM4ZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: questcode
  namespace: prod
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly90amNhMTp0MTIzNDU2QGNsdXN0ZXIwLTlqYmJlLm1vbmdvZGIubmV0L3Rlc3RfP3JldHJ5V3JpdGVzPXRydWUmdXNlTmV3VXJsUGFyc2VyPXRydWUK
  SECRET_OR_KEY: NjA0Mjk4NmE5YjM5ZjE1ZjI1YTM=
  GITHUB_CLIENT_SECRET: M2M4MmNmNjM5NmJlYjY4OWRkYmFlYWJhNGQ2YjYzNDYwMDI5NGM4ZA==

  